version: "3.9"

services:
  redis:
    image: redis:7.2
    container_name: weather_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .. 
    container_name: weather_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ..:/app
      
  frontend:
    build: ..
    container_name: weather_streamlit
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    volumes:
      - ..:/app
    command: ["streamlit", "run", "src/app/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]

volumes:
  redis_data: